### ISSUE TITLE
File is not under the client root

### ISSUE THREAD

**Issue by nomaed** [ericmartel/Sublime-Text-3-Perforce-Plugin#10]
Hi.

I've been using your p4 plugin for ST3 for a while now and I have to say it's really great. Making work much easier! So thank you for that.

Recently though, I moved from CentOS 6.5 to a new Linux installation (Ubuntu 14.04), set up perforce, installed ST3 with the plugin and started working on a file in the p4 root.
However, this time the plugin doesn't recognize that I'm in the client root.

p4 (and p4v) work without any problem. I am 100% sure that the files are inside the client root (everything is fine from command-line).

Can't seem to find any online information (in the context of the plugin) about it either.

Have you heard of similar issues occuring?
I can send you my p4 info or any other details that you might need.

Thank you,
Boris.

**Comment by robotgoblin** [comment]
@JLoppert's solution of creating the symlink worked for me too!

Perhaps this could me mentioned in the README, or the script could search elsewhere for the binary?

**Comment by ericmartel** [comment]
Considering the script is cross platform, I'm not too confortable doing error "recovery" for each platform but you are right, this should be part of the readme
