### ISSUE TITLE
file is not under client root sublime3 and windows

### ISSUE THREAD

**Issue by omatic-hacker** [ericmartel/Sublime-Text-3-Perforce-Plugin#13]
Hello Eric,

Thanks for good job on plugin. This is what I’ve always searched for sublime, but I’ve got a question, how can I properly configure it to work with perforce?

Cause currently I’ve got an error: “file is not under client root”

IDE: Sublime Text 3 (C:\Program Files\Sublime Text 3)
OS: Windows 7
Perforce: C:\Program Files\Perforce

p4 is in PATH, and from cmd p4 is working.

========================
p4 SET
========================

P4CLIENT=myworkspace
P4EDITOR=C:\Program Files\Sublime Text 3\sublime_text.exe
P4IGNORE=.p4ignore
P4PASSWD=mypassword
P4PORT=perforce.server:port
P4USER=myusername
P4_perforce.server:port_CHARSET=none

========================
workspace
========================
name: myworkspace
root: C:\Users\my.user\Perforce\myworkspace\

I would greatly appreciate any help you can give me in working this problem.

**Comment by mi-lad** [comment]
Try defining a P4CONFIG variable and then populate that config file in your workspace root

**Comment by omatic-hacker** [comment]
**mi-lad**, just to clarify, is my steps correct? Cause that not helped. Same error: “file is not under client root”

1. Create file: p4config.txt
2. Put all config data to it:
```
P4CLIENT=myworkspace
P4EDITOR=C:\Program Files\Sublime Text 3\sublime_text.exe
P4IGNORE=.p4ignore
P4PASSWD=mypassword
P4PORT=perforce.server:port
P4USER=myusername
P4_perforce.server:port_CHARSET=none
```
3. Put file to  C:\Users\my.user\Perforce\myworkspace\
4. p4 set P4CONFIG=p4config.txt

p4 SET
===============================
```
P4CLIENT=myworkspace (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt')
P4CONFIG=p4config.txt (set) (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt' )
P4EDITOR=C:\Program Files\Sublime Text 3\sublime_text.exe (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt')
P4IGNORE=.p4ignore (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt')
P4PASSWD=mypassword (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt')
P4PORT=perforce.server:port (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt')
P4USER=myusername (config 'C:\Users\my.user\Perforce\myworkspace\p4config.txt')
P4_perforce.server:port_CHARSET=none (config C:\Users\my.user\Perforce\myworkspace\p4config.txt')
```

**Comment by mi-lad** [comment]
@omatic-hacker I'm not sure if "p4 SET" stuff propagates to Sublime. What worked for me was defining P4CONFIG in my shell (.zshrc or .bashrc), then cd into to my workspace and do a "p4 login". Once it says it's logged in, I start sublime from the same shell.

**Comment by omatic-hacker** [comment]
@mi-lad I can login from cmd with "p4 login" too. But I was using "p4 set" cause there is no shell config in Windows.

I believe that Sublime in Windows just don't find path to p4 or something else, maybe someone know how to configure it like in linux shell?? 
Where plugin gets the info about p4? Cause command p4 info works ok in cmd as well.

**Comment by mi-lad** [comment]
@omatic-hacker I have not tried it in Windows. In Linux I get “file is not under client root” when sublime does not see my P4CONFIG. Maybe try defining the "perforce_p4env" setting in plugin settings in Sublime?

**Comment by omatic-hacker** [comment]
@mi-lad Tried to define it in ***Perforce.sublime-settings***, but it didn't helped too:
```
"perforce_p4env": "C:\\Users\\my.username\\Perforce\\myworkspace\\p4config.txt"
```

**Comment by omatic-hacker** [comment]
This is weird, I've looked at plugin source code, method ConstructCommand and found that it is not working properly with perforce_p4env 
```
command = '. {0} && '.format(p4Env)
```
I will check how to fix this, but permanently I've just changed setting parameter to: 
```
"perforce_p4env": ""
```
and plugin started to use p4 set environment options. Look's good for now. 

@mi-lad Thanks for comments and help.
