### ISSUE TITLE
Environment settings are erased.

### ISSUE THREAD

**Issue by ssouffri** [ericmartel/Sublime-Text-3-Perforce-Plugin#19]
Regarding v2016.06.19.20.44.38 on Windows 7.

When opening sublime my P4 environment values have the correct value in the console:

> > > import os
> > > print([(k,v) for k,v in os.environ.items() if "P4" in k])
> > > [('P4USER', 'stso'), ('P4PORT', 'zel-as01.greenpeak.com:1666'), ('P4CLIENT', 'LAPTOP-HP-STSO')]

When trying to checkout a file form the Tools -> Perforce -> Checkout menu I get: 

```
     "Perforce warning: file not under client root!"
```

When I check the environment again I see:

> > > import os
> > > print([(k,v) for k,v in os.environ.items() if "P4" in k])
> > > [('P4USER', 'P4USER'), ('P4PORT', 'P4PORT'), ('P4CLIENT', 'P4CLIENT')]

So it looks like the plugin is erasing the environment settings! The checkout option in the menu is disabled from then on.

**Comment by ericmartel** [comment]
Hi!

That's very peculiar, I'll need to investigate it as I don't recall the
plugin changing anything on the system.  I'm currently on my honeymoon, so
I apologize for the delays

Eric

**Comment by ssouffri** [comment]
Hi Eric,

Didn't mean to disturb your honeymoon. Congratulations!
Just to be more clear: when I said console, I meant the Sublime console.

Stijn

**Comment by ssouffri** [comment]
After some more experimenting I found that disabling the "P4Gutter" plugin fixes the issue.  In other words it was not the "Perforce" plugin that was causing the P4 environment settings to be erased.

**Comment by ericmartel** [comment]
Oh that's good news!  I'm back home now but I'm glad you figured out the
issue!  Thanks for updating the ticket

Eric
