### ISSUE TITLE
Saving Perforce.sublime-settings - User Hangs Sublime Text

### ISSUE THREAD

**Issue by bstoots** [ericmartel/Sublime-Text-3-Perforce-Plugin#24]
I'm having an issue when I attempt to save the Perforce.sublime-settings in order to make modifications.  I tried just copy / pasting the default config text into the empty user specific settings file but when I hit save Sublime Text hangs indefinitely.  The plugin actually works out of the box with the default settings but I was curious if you had ever seen this behavior before or had any suggestions.

Thanks for this plugin by the way, it's saving me a bunch of time already.

**Comment by ericmartel** [comment]
Hi!

I haven't used Sublime + Perforce in years so I'm not sure if there's something new that I'm not aware of!  

Shouldn't your user specific settings all go in Preferences.sublime-settings ?

I wish I had a P4 server I could experiment with to help you with your issue but I don't at the moment :(

**Comment by bstoots** [comment]
I was able to work around this issue.  I think it may have just been a remote file system issue.
